# Generated by Django 3.2.13 on 2023-04-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='teacher',
        ),
        migrations.AddField(
            model_name='students',
            name='teacher',
            field=models.ManyToManyField(to='app.Teacher'),
        ),
    ]
